version: '3.8'

services:
  postgres-test:
    image: postgres:15
    environment:
      POSTGRES_DB: techze_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-test:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  diagnostic-service-test:
    build:
      context: ./microservices/diagnostic_service
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:test_password@postgres-test:5432/techze_test
      - REDIS_URL=redis://redis-test:6379
      - ENVIRONMENT=test
      - SECRET_KEY=test-secret-key-for-ci
    ports:
      - "8001:8000"
    depends_on:
      postgres-test:
        condition: service_healthy
      redis-test:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_test_data: