services:
  - type: web
    name: techze-diagnostico-api
    env: python
    plan: free
    buildCommand: cd microservices/diagnostic_service && pip install -r requirements.txt && chmod +x start.sh
    startCommand: cd microservices/diagnostic_service && ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: ENVIRONMENT
        value: production
      - key: LOG_LEVEL
        value: info
      - key: SUPABASE_URL
        fromSecret: SUPABASE_URL
      - key: SUPABASE_ANON_KEY
        fromSecret: SUPABASE_ANON_KEY
      - key: SUPABASE_SERVICE_ROLE_KEY
        fromSecret: SUPABASE_SERVICE_ROLE_KEY
      - key: JWT_SECRET_KEY
        fromSecret: JWT_SECRET_KEY
      - key: JWT_ALGORITHM
        value: HS256
      - key: JWT_ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: REDIS_URL
        fromSecret: REDIS_URL
      - key: SENTRY_DSN
        fromSecret: SENTRY_DSN
      - key: RATE_LIMIT_PER_MINUTE
        value: 60
      - key: MAX_REQUESTS_PER_HOUR
        value: 1000
      - key: CORS_ORIGINS
        value: "*"
    autoDeploy: true
    healthCheckPath: /health

  - type: web
    name: techze-diagnostico-frontend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run preview -- --host 0.0.0.0 --port $PORT
    envVars:
      - key: NODE_VERSION
        value: 22.14.0
      - key: VITE_API_URL
        value: https://techze-diagnostico-api.onrender.com
      - key: VITE_SUPABASE_URL
        fromSecret: SUPABASE_URL
      - key: VITE_SUPABASE_ANON_KEY
        fromSecret: SUPABASE_ANON_KEY
    autoDeploy: true
    healthCheckPath: /