// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://waxnnwpsvitmeeivkwkn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndheG5ud3Bzdml0bWVlaXZrd2tuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MTA1MDcsImV4cCI6MjA2NDE4NjUwN30.faxEG4xqXXW9eJv6MLkLl6UEU6dayz336Qqak_1nlII";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);